### ISSUE TITLE
Two questions about rscala

### ISSUE THREAD

**Issue by bithw1** [dbdahl/rscala#1]
With the following code, I got two questions:

```
object RScala2Test {
  def main(args: Array[String]): Unit = {
    val R = org.ddahl.rscala.RClient()
    R eval """
    print("Hello, I am in Scala")
    """.stripMargin(' ')

   R eval """
    1 / "a"
    """ .stripMargin(' ')
  }
}
```

1. The first question is that I can' see the output of     **_print("Hello, I am in Scala")_,** If the R script is very long,it would very helpful to see what's going on in R with _print_,

2. The second question is that i deliberately write the code **_1 / "a"_** that will cause error, the output is as follows:

_��������������з���ֵ����
Exception in thread "main" java.lang.RuntimeException: Error in R evaluation.
	at org.ddahl.rscala.RClient.eval(RClient.scala:112)
	at org.ddahl.rscala.RClient.eval(RClient.scala:117)
	at rscala.RScala2Test$.main(RScala2Test.scala:12)
	at rscala.RScala2Test.main(RScala2Test.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)_

There is messy code in the first line, I am not sure what it is saying, and what cause it.
1. Is it the error message that exactly shows what's wrong in the R code?
2. I am in Intellij Idea, which is using UTF-8,and I am not sure what's causing this

**Comment by dbdahl** [comment]
These issues are resolved by asking the RClient to serialized output from R using the "serializedOutput" argument, e.g.:

`val R = org.ddahl.rscala.RClient(serializeOutput=true)`

**Comment by bithw1** [comment]
Thanks @dbdahl  for the helpful answer, this exactly what I want, thanks!
